var equipe = [
    [`1. Bundesliga`,`https://oraculo.wederson.net.br/alemanha/imagem/ale1.png`,,0],
    
    [`Augsburg`,`https://oraculo.wederson.net.br/alemanha/imagem/augsburg.png`,
        {a:11/10,d:10/10},1],
    [`Union Berlin`,`https://oraculo.wederson.net.br/alemanha/imagem/berlin.png`,
        {a:9/10,d:21/10},2],
    [`Bochum`,`https://oraculo.wederson.net.br/alemanha/imagem/bochum.png`,
        {a:11/10,d:13/10},3],
    [`Werder Bremen`,`https://oraculo.wederson.net.br/alemanha/imagem/werder.png`,
        {a:14/10,d:25/10},4],
    [`Dortmund`,`https://oraculo.wederson.net.br/alemanha/imagem/dortmund.png`,
        {a:20/10,d:17/10},5],
    [`Eintracht`,`https://oraculo.wederson.net.br/alemanha/imagem/eintracht.png`,
        {a:16/10,d:17/10},6],
    [`Freiburg`,`https://oraculo.wederson.net.br/alemanha/imagem/freiburg.png`,
        {a:17/10,d:19/10},7],
    [`Heidenheim`,`https://oraculo.wederson.net.br/alemanha/imagem/heidenheim.png`,
        {a:9/10,d:19/10},8],
    [`Hoffenheim`,`https://oraculo.wederson.net.br/alemanha/imagem/hoffenheim.png`,
        {a:12/10,d:20/10},9],
    [`Holstein Kiel`,`https://oraculo.wederson.net.br/alemanha/imagem/holsteinkiel.png`,
        {a:21/10,d:26/10},10],
    [`RB Leipzig`,`https://oraculo.wederson.net.br/alemanha/imagem/leipzig.png`,
        {a:16/10,d:18/10},11],
    [`Leverkusen`,`https://oraculo.wederson.net.br/alemanha/imagem/leverkusen.png`,
        {a:23/10,d:8/10},12],
    [`Mainz 05`,`https://oraculo.wederson.net.br/alemanha/imagem/mainz.png`,
        {a:14/10,d:6/10},13],
    [`Mönchengladbach`,`https://oraculo.wederson.net.br/alemanha/imagem/monchengladbach.png`,
        {a:15/10,d:16/10},14],
    [`Bayern`,`https://oraculo.wederson.net.br/alemanha/imagem/bayern.png`,
        {a:30/10,d:8/10},15],
    [`St. Pauli`,`https://oraculo.wederson.net.br/alemanha/imagem/stpauli.png`,
        {a:7/10,d:10/10},16],
    [`Stuttgart`,`https://oraculo.wederson.net.br/alemanha/imagem/stuttgart.png`,
        {a:13/10,d:13/10},17],
    [`Wolfsburg`,`https://oraculo.wederson.net.br/alemanha/imagem/wolfsburg.png`,
        {a:17/10,d:13/10},18]
]

var tabelaRRinicial = [
    [equipe[0][0],equipe[1][0],equipe[2][0],equipe[3][0],equipe[4][0],equipe[5][0],equipe[6][0],equipe[7][0],equipe[8][0],equipe[9][0],equipe[10][0],equipe[11][0],equipe[12][0],equipe[13][0],equipe[14][0],equipe[15][0],equipe[16][0],equipe[17][0],equipe[18][0]],
    [equipe[1][0],[,]/*AUG */,[,]/*UNB */,[1,0]/*BOC */,[2,2]/*BRE */,[2,1]/*DOR */,[,]/*FRA */,[,]/*FRE */,[2,1]/*HEI */,[0,0]/*HOF */,[,]/*KIE */,[0,0]/*LEI */,[0,2]/*LEV */,[2,3]/*MAI */,[2,1]/*MÖN */,[,]/*MUN */,[3,1]/*STP */,[0,1]/*STU */,[,]/*WOL */],
    [equipe[2][0],[0,2]/*AUG */,[,]/*UNB */,[0,0]/*BOC */,[,]/*BRE */,[2,1]/*DOR */,[1,1]/*FRA */,[0,0]/*FRE */,[,]/*HEI */,[2,1]/*HOF */,[,]/*KIE */,[0,0]/*LEI */,[1,2]/*LEV */,[2,1]/*MAI */,[1,2]/*MÖN */,[,]/*MUN */,[1,0]/*STP */,[,]/*STU */,[,]/*WOL */],
    [equipe[3][0],[,]/*AUG */,[,]/*UNB */,[,]/*BOC */,[0,1]/*BRE */,[2,0]/*DOR */,[,]/*FRA */,[0,1]/*FRE */,[2,0]/*HEI */,[,]/*HOF */,[2,2]/*KIE */,[3,3]/*LEI */,[1,1]/*LEV */,[,]/*MAI */,[0,2]/*MÖN */,[0,5]/*MUN */,[1,0]/*STP */,[,]/*STU */,[1,3]/*WOL */],
    [equipe[4][0],[0,2]/*AUG */,[4,1]/*UNB */,[,]/*BOC */,[,]/*BRE */,[0,0]/*DOR */,[,]/*FRA */,[0,1]/*FRE */,[3,3]/*HEI */,[1,3]/*HOF */,[2,1]/*KIE */,[,]/*LEI */,[2,2]/*LEV */,[1,0]/*MAI */,[,]/*MÖN */,[0,5]/*MUN */,[,]/*STP */,[2,2]/*STU */,[,]/*WOL */],
    [equipe[5][0],[,]/*AUG */,[6,0]/*UNB */,[4,2]/*BOC */,[2,2]/*BRE */,[,]/*DOR */,[2,0]/*FRA */,[4,0]/*FRE */,[4,2]/*HEI */,[1,1]/*HOF */,[,]/*KIE */,[2,1]/*LEI */,[2,3]/*LEV */,[,]/*MAI */,[,]/*MÖN */,[1,1]/*MUN */,[2,1]/*STP */,[1,2]/*STU */,[,]/*WOL */],
    [equipe[6][0],[2,2]/*AUG */,[,]/*UNB */,[7,2]/*BOC */,[1,0]/*BRE */,[2,0]/*DOR */,[,]/*FRA */,[4,1]/*FRE */,[,]/*HEI */,[3,1]/*HOF */,[3,1]/*KIE */,[,]/*LEI */,[,]/*LEV */,[1,3]/*MAI */,[2,0]/*MÖN */,[3,3]/*MUN */,[,]/*STP */,[,]/*STU */,[1,1]/*WOL */],
    [equipe[7][0],[3,1]/*AUG */,[,]/*UNB */,[2,1]/*BOC */,[5,0]/*BRE */,[,]/*DOR */,[,]/*FRA */,[,]/*FRE */,[1,0]/*HEI */,[,]/*HOF */,[3,2]/*KIE */,[,]/*LEI */,[,]/*LEV */,[0,0]/*MAI */,[3,1]/*MÖN */,[1,2]/*MUN */,[0,3]/*STP */,[3,1]/*STU */,[3,2]/*WOL */],
    [equipe[8][0],[4,0]/*AUG */,[2,0]/*UNB */,[,]/*BOC */,[,]/*BRE */,[1,2]/*DOR */,[0,4]/*FRA */,[0,3]/*FRE */,[,]/*HEI */,[0,0]/*HOF */,[,]/*KIE */,[0,1]/*LEI */,[,]/*LEV */,[0,2]/*MAI */,[,]/*MÖN */,[,]/*MUN */,[0,2]/*STP */,[1,3]/*STU */,[1,3]/*WOL */],
    [equipe[9][0],[,]/*AUG */,[0,4]/*UNB */,[3,1]/*BOC */,[3,4]/*BRE */,[,]/*DOR */,[2,2]/*FRA */,[1,1]/*FRE */,[,]/*HEI */,[,]/*HOF */,[3,2]/*KIE */,[4,3]/*LEI */,[1,4]/*LEV */,[,]/*MAI */,[1,2]/*MÖN */,[,]/*MUN */,[0,2]/*STP */,[1,1]/*STU */,[0,1]/*WOL */],
    [equipe[10][0],[5,1]/*AUG */,[0,2]/*UNB */,[2,2]/*BOC */,[,]/*BRE */,[4,2]/*DOR */,[2,4]/*FRA */,[,]/*FRE */,[1,0]/*HEI */,[1,3]/*HOF */,[,]/*KIE */,[0,2]/*LEI */,[0,2]/*LEV */,[0,3]/*MAI */,[,]/*MÖN */,[1,6]/*MUN */,[,]/*STP */,[,]/*STU */,[0,2]/*WOL */],
    [equipe[11][0],[4,0]/*AUG */,[0,0]/*UNB */,[1,0]/*BOC */,[4,2]/*BRE */,[,]/*DOR */,[2,1]/*FRA */,[3,1]/*FRE */,[2,2]/*HEI */,[,]/*HOF */,[,]/*KIE */,[,]/*LEI */,[2,2]/*LEV */,[,]/*MAI */,[0,0]/*MÖN */,[,]/*MUN */,[2,0]/*STP */,[,]/*STU */,[1,5]/*WOL */],
    [equipe[12][0],[,]/*AUG */,[,]/*UNB */,[,]/*BOC */,[,]/*BRE */,[,]/*DOR */,[2,1]/*FRA */,[5,1]/*FRE */,[5,2]/*HEI */,[3,1]/*HOF */,[2,2]/*KIE */,[2,3]/*LEI */,[,]/*LEV */,[1,0]/*MAI */,[3,1]/*MÖN */,[0,0]/*MUN */,[2,1]/*STP */,[0,0]/*STU */,[4,3]/*WOL */],
    [equipe[13][0],[0,0]/*AUG */,[1,1]/*UNB */,[2,0]/*BOC */,[1,2]/*BRE */,[3,1]/*DOR */,[,]/*FRA */,[,]/*FRE */,[0,2]/*HEI */,[2,0]/*HOF */,[,]/*KIE */,[0,2]/*LEI */,[,]/*LEV */,[,]/*MAI */,[1,1]/*MÖN */,[2,1]/*MUN */,[2,0]/*STP */,[2,0]/*STU */,[,]/*WOL */],
    [equipe[14][0],[0,3]/*AUG */,[1,0]/*UNB */,[3,0]/*BOC */,[4,1]/*BRE */,[1,1]/*DOR */,[1,1]/*FRA */,[,]/*FRE */,[3,2]/*HEI */,[,]/*HOF */,[4,1]/*KIE */,[,]/*LEI */,[2,3]/*LEV */,[,]/*MAI */,[,]/*MÖN */,[0,1]/*MUN */,[2,0]/*STP */,[1,3]/*STU */,[,]/*WOL */],
    [equipe[15][0],[3,0]/*AUG */,[3,0]/*UNB */,[,]/*BOC */,[3,0]/*BRE */,[,]/*DOR */,[4,0]/*FRA */,[2,0]/*FRE */,[4,2]/*HEI */,[5,0]/*HOF */,[4,3]/*KIE */,[5,1]/*LEI */,[1,1]/*LEV */,[,]/*MAI */,[,]/*MÖN */,[,]/*MUN */,[,]/*STP */,[4,0]/*STU */,[3,2]/*WOL */],
    [equipe[16][0],[1,1]/*AUG */,[3,0]/*UNB */,[,]/*BOC */,[0,2]/*BRE */,[,]/*DOR */,[0,1]/*FRA */,[0,1]/*FRE */,[0,2]/*HEI */,[,]/*HOF */,[3,1]/*KIE */,[0,0]/*LEI */,[,]/*LEV */,[0,3]/*MAI */,[,]/*MÖN */,[0,1]/*MUN */,[,]/*STP */,[,]/*STU */,[0,0]/*WOL */],
    [equipe[17][0],[,]/*AUG */,[3,2]/*UNB */,[2,0]/*BOC */,[,]/*BRE */,[5,1]/*DOR */,[2,3]/*FRA */,[4,0]/*FRE */,[,]/*HEI */,[1,1]/*HOF */,[2,1]/*KIE */,[2,1]/*LEI */,[,]/*LEV */,[3,3]/*MAI */,[1,2]/*MÖN */,[,]/*MUN */,[0,1]/*STP */,[,]/*STU */,[1,2]/*WOL */],
    [equipe[18][0],[1,1]/*AUG */,[1,0]/*UNB */,[1,1]/*BOC */,[2,4]/*BRE */,[1,3]/*DOR */,[1,2]/*FRA */,[,]/*FRE */,[,]/*HEI */,[,]/*HOF */,[2,2]/*KIE */,[,]/*LEI */,[0,0]/*LEV */,[4,3]/*MAI */,[5,1]/*MÖN */,[2,3]/*MUN */,[,]/*STP */,[2,2]/*STU */,[,]/*WOL */]
]