var rodat = 10
var equipe = [
    [`Brasileirão Série A`,`http://oraculo.wederson.com/brasil/imagem/div1.png`,,0],
    
    [`América`,`http://oraculo.wederson.com/brasil/imagem/americamg.png`,
       {
            a:12/rodat,
            d:24/rodat,
            rat:1932
        },0],
    [`Athlético`,`http://oraculo.wederson.com/brasil/imagem/athletico.png`,
        {
            a:11/rodat,
            d:9/rodat,
            rat:1932
        },1],
    [`Atlético`,`http://oraculo.wederson.com/brasil/imagem/atletico.png`,
        {
            a:19/rodat,
            d:7/rodat,
            rat:1932
        },2],
    [`Bahia`,`http://oraculo.wederson.com/brasil/imagem/bahia.png`,
        {
            a:11/rodat,
            d:14/rodat,
            rat:1932
        },4],
    [`Botafogo`,`http://oraculo.wederson.com/brasil/imagem/botafogo.png`,
        {
            a:13/rodat,
            d:17/rodat,
            rat:1932
        },5],
    [`Corinthians`,`http://oraculo.wederson.com/brasil/imagem/corinthians.png`,
        {
            a:12/rodat,
            d:13/rodat,
            rat:1932
        },6],
    [`Coritiba`,`http://oraculo.wederson.com/brasil/imagem/coritiba.png`,
        {
            a:12/rodat,
            d:14/rodat,
            rat:1932
        },7],
    [`Cruzeiro`,`http://oraculo.wederson.com/brasil/imagem/cruzeiro.png`,
        {
            a:10/rodat,
            d:7/rodat,
            rat:1932
        },8],
    [`Cuiabá`,`http://oraculo.wederson.com/brasil/imagem/cuiaba.png`,
        {
            a:8/rodat,
            d:9/rodat,
            rat:1932
        },9],
    [`Flamengo`,`http://oraculo.wederson.com/brasil/imagem/flamengo.png`,
        {
            a:16/rodat,
            d:10/rodat,
            rat:1932
        },10],
    [`Fluminense`,`http://oraculo.wederson.com/brasil/imagem/fluminense.png`,
        {
            a:12/rodat,
            d:10/rodat,
            rat:1932
        },11],
    [`Fortaleza`,`http://oraculo.wederson.com/brasil/imagem/fortaleza.png`,
        {
            a:10/rodat,
            d:16/rodat,
            rat:1932
        },12],
    [`Goiás`,`http://oraculo.wederson.com/brasil/imagem/goias.png`,
        {
            a:8/rodat,
            d:16/rodat,
            rat:1932
        },13],
    [`Grêmio`,`http://oraculo.wederson.com/brasil/imagem/gremio.png`,
        {
            a:17/rodat,
            d:17/rodat,
            rat:1932
        },14],
    [`Internacional`,`http://oraculo.wederson.com/brasil/imagem/internacional.png`,
        {
            a:20/rodat,
            d:12/rodat,
            rat:1932
        },15],
    [`Palmeiras`,`http://oraculo.wederson.com/brasil/imagem/palmeiras.png`,
        {
            a:23/rodat,
            d:8/rodat,
            rat:1932
        },16],
    [`Red Bull`,`http://oraculo.wederson.com/brasil/imagem/redbull.png`,
        {
            a:9/rodat,
            d:9/rodat,
            rat:1932
        },17],
    [`Santos`,`http://oraculo.wederson.com/brasil/imagem/santos.png`,
        {
            a:8/rodat,
            d:17/rodat,
            rat:1932
        },18],
    [`São Paulo`,`http://oraculo.wederson.com/brasil/imagem/saopaulo.png`,
        {
            a:8/rodat,
            d:9/rodat,
            rat:1932
        },19],
    [`Vasco`,`http://oraculo.wederson.com/brasil/imagem/vasco.png`,
        {
            a:11/rodat,
            d:12/rodat,
            rat:1932
        },20],
]