var equipe = [
    [`Eredivisie`,`https://oraculo.wederson.net.br/neerlandia/imagem/nne1.png`,,0],
    
    [`Ajax`,`https://oraculo.wederson.net.br/neerlandia/imagem/ajax.png`,
        {a:22/10,d:5/10},1],
    [`Almere`,`https://oraculo.wederson.net.br/neerlandia/imagem/almere.png`,
        {a:9/10,d:17/10},2],
    [`AZ`,`https://oraculo.wederson.net.br/neerlandia/imagem/az.png`,
        {a:14/10,d:6/10},3],
    [`Feyenoord`,`https://oraculo.wederson.net.br/neerlandia/imagem/feyenoord.png`,
        {a:17/10,d:14/10},4],
    [`Fortuna Sittard`,`https://oraculo.wederson.net.br/neerlandia/imagem/fortuna.png`,
        {a:16/10,d:23/10},5],
    [`Go Ahed Eagles`,`https://oraculo.wederson.net.br/neerlandia/imagem/gae.png`,
        {a:23/10,d:15/10},6],
    [`Groningen`,`https://oraculo.wederson.net.br/neerlandia/imagem/groningen.png`,
        {a:9/10,d:9/10},7],
    [`Heereveen`,`https://oraculo.wederson.net.br/neerlandia/imagem/heereveen.png`,
        {a:14/10,d:16/10},8],
    [`Heracles Almelo`,`https://oraculo.wederson.net.br/neerlandia/imagem/heracles.png`,
        {a:14/10,d:18/10},9],
    [`NAC Breda`,`https://oraculo.wederson.net.br/neerlandia/imagem/nacbreda.png`,
        {a:11/10,d:19/10},10],
    [`NEC`,`https://oraculo.wederson.net.br/neerlandia/imagem/nec.png`,
        {a:14/10,d:22/10},11],
    [`PEC Zwolle`,`https://oraculo.wederson.net.br/neerlandia/imagem/zwolle.png`,
        {a:13/10,d:11/10},12],
    [`PSV`,`https://oraculo.wederson.net.br/neerlandia/imagem/psv.png`,
        {a:23/10,d:18/10},13],
    [`Waalwijk`,`https://oraculo.wederson.net.br/neerlandia/imagem/waalwijk.png`,
        {a:19/10,d:15/10},14],
    [`Sparta Rotterdam`,`https://oraculo.wederson.net.br/neerlandia/imagem/sparta.png`,
        {a:6/10,d:13/10},15],
    [`Twente`,`https://oraculo.wederson.net.br/neerlandia/imagem/twente.png`,
        {a:20/10,d:17/10},16],
    [`Utrecht`,`https://oraculo.wederson.net.br/neerlandia/imagem/utrecht.png`,
        {a:17/10,d:17/10},17],
    [`Willem II`,`https://oraculo.wederson.net.br/neerlandia/imagem/willem.png`,
        {a:11/10,d:20/10},18]
]

var tabelaRRinicial = [
[equipe[0][0],equipe[1][0],equipe[2][0],equipe[3][0],equipe[4][0],equipe[5][0],equipe[6][0],equipe[7][0],equipe[8][0],equipe[9][0],equipe[10][0],equipe[11][0],equipe[12][0],equipe[13][0],equipe[14][0],equipe[15][0],equipe[16][0],equipe[17][0],equipe[18][0]],
[equipe[1][0],[,]/*AJA */,[3,0]/*ALM */,[,]/*AZ */,[2,1]/*FEY */,[5,0]/*FOR */,[2,0]/*GAE */,[3,1]/*GRO */,[1,0]/*HEE */,[4,0]/*HER */,[,]/*NAC */,[,]/*NEC */,[2,0]/*PEC */,[3,2]/*PSV */,[2,1]/*RKC */,[,]/*SPA */,[,]/*TWE */,[2,2]/*UTR */,[1,0]/*WIL */],
[equipe[2][0],[,]/*AJA */,[,]/*ALM */,[0,1]/*AZ */,[1,4]/*FEY */,[,]/*FOR */,[,]/*GAE */,[1,1]/*GRO */,[3,0]/*HEE */,[0,2]/*HER */,[,]/*NAC */,[1,0]/*NEC */,[,]/*PEC */,[1,7]/*PSV */,[1,4]/*RKC */,[,]/*SPA */,[0,5]/*TWE */,[1,3]/*UTR */,[0,1]/*WIL */],
[equipe[3][0],[2,1]/*AJA */,[,]/*ALM */,[,]/*AZ */,[,]/*FEY */,[1,0]/*FOR */,[2,2]/*GAE */,[,]/*GRO */,[9,1]/*HEE */,[1,0]/*HER */,[,]/*NAC */,[1,0]/*NEC */,[2,0]/*PEC */,[1,2]/*PSV */,[,]/*RKC */,[1,2]/*SPA */,[1,0]/*TWE */,[1,2]/*UTR */,[1,2]/*WIL */],
[equipe[4][0],[0,2]/*AJA */,[2,1]/*ALM */,[3,2]/*AZ */,[,]/*FEY */,[1,1]/*FOR */,[,]/*GAE */,[,]/*GRO */,[3,0]/*HEE */,[5,2]/*HER */,[2,0]/*NAC */,[,]/*NEC */,[,]/*PEC */,[,]/*PSV */,[,]/*RKC */,[3,0]/*SPA */,[2,1]/*TWE */,[1,2]/*UTR */,[1,1]/*WIL */],
[equipe[5][0],[0,2]/*AJA */,[3,0]/*ALM */,[1,0]/*AZ */,[,]/*FEY */,[,]/*FOR */,[0,3]/*GAE */,[1,0]/*GRO */,[3,0]/*HEE */,[,]/*HER */,[,]/*NAC */,[0,3]/*NEC */,[1,4]/*PEC */,[1,3]/*PSV */,[3,2]/*RKC */,[,]/*SPA */,[1,2]/*TWE */,[,]/*UTR */,[,]/*WIL */],
[equipe[6][0],[1,1]/*AJA */,[3,0]/*ALM */,[,]/*AZ */,[1,5]/*FEY */,[0,2]/*FOR */,[,]/*GAE */,[2,1]/*GRO */,[,]/*HEE */,[4,1]/*HER */,[2,1]/*NAC */,[5,0]/*NEC */,[2,2]/*PEC */,[3,2]/*PSV */,[2,0]/*RKC */,[1,0]/*SPA */,[2,2]/*TWE */,[,]/*UTR */,[,]/*WIL */],
[equipe[7][0],[,]/*AJA */,[0,0]/*ALM */,[0,0]/*AZ */,[2,2]/*FEY */,[,]/*FOR */,[0,1]/*GAE */,[,]/*GRO */,[1,0]/*HEE */,[,]/*HER */,[4,1]/*NAC */,[2,1]/*NEC */,[0,0]/*PEC */,[,]/*PSV */,[,]/*RKC */,[1,0]/*SPA */,[,]/*TWE */,[0,1]/*UTR */,[2,0]/*WIL */],
[equipe[8][0],[0,2]/*AJA */,[,]/*ALM */,[,]/*AZ */,[,]/*FEY */,[2,2]/*FOR */,[1,0]/*GAE */,[2,1]/*GRO */,[,]/*HEE */,[,]/*HER */,[4,0]/*NAC */,[,]/*NEC */,[1,1]/*PEC */,[1,0]/*PSV */,[1,1]/*RKC */,[2,0]/*SPA */,[3,3]/*TWE */,[1,1]/*UTR */,[,]/*WIL */],
[equipe[9][0],[3,4]/*AJA */,[0,0]/*ALM */,[,]/*AZ */,[,]/*FEY */,[2,2]/*FOR */,[,]/*GAE */,[1,1]/*GRO */,[2,1]/*HEE */,[,]/*HER */,[2,0]/*NAC */,[,]/*NEC */,[,]/*PEC */,[1,3]/*PSV */,[2,2]/*RKC */,[1,1]/*SPA */,[,]/*TWE */,[1,1]/*UTR */,[1,1]/*WIL */],
[equipe[10][0],[2,1]/*AJA */,[1,0]/*ALM */,[1,2]/*AZ */,[0,0]/*FEY */,[1,0]/*FOR */,[,]/*GAE */,[,]/*GRO */,[2,4]/*HEE */,[1,1]/*HER */,[,]/*NAC */,[1,0]/*NEC */,[,]/*PEC */,[0,3]/*PSV */,[4,1]/*RKC */,[,]/*SPA */,[2,1]/*TWE */,[1,2]/*UTR */,[,]/*WIL */],
[equipe[11][0],[1,2]/*AJA */,[2,2]/*ALM */,[,]/*AZ */,[1,1]/*FEY */,[4,1]/*FOR */,[,]/*GAE */,[6,0]/*GRO */,[3,0]/*HEE */,[1,2]/*HER */,[,]/*NAC */,[,]/*NEC */,[1,0]/*PEC */,[3,3]/*PSV */,[,]/*RKC */,[1,1]/*SPA */,[1,2]/*TWE */,[1,2]/*UTR */,[,]/*WIL */],
[equipe[12][0],[,]/*AJA */,[1,0]/*ALM */,[1,2]/*AZ */,[1,5]/*FEY */,[3,1]/*FOR */,[,]/*GAE */,[,]/*GRO */,[1,1]/*HEE */,[3,0]/*HER */,[1,2]/*NAC */,[0,1]/*NEC */,[,]/*PEC */,[3,1]/*PSV */,[,]/*RKC */,[1,0]/*SPA */,[,]/*TWE */,[3,3]/*UTR */,[0,1]/*WIL */],
[equipe[13][0],[,]/*AJA */,[,]/*ALM */,[2,2]/*AZ */,[3,0]/*FEY */,[,]/*FOR */,[3,0]/*GAE */,[5,0]/*GRO */,[,]/*HEE */,[,]/*HER */,[3,2]/*NAC */,[2,0]/*NEC */,[6,0]/*PEC */,[,]/*PSV */,[5,1]/*RKC */,[2,1]/*SPA */,[6,1]/*TWE */,[2,2]/*UTR */,[1,1]/*WIL */],
[equipe[14][0],[0,2]/*AJA */,[2,0]/*ALM */,[0,3]/*AZ */,[2,3]/*FEY */,[1,2]/*FOR */,[,]/*GAE */,[1,2]/*GRO */,[,]/*HEE */,[,]/*HER */,[5,0]/*NAC */,[0,3]/*NEC */,[1,1]/*PEC */,[,]/*PSV */,[,]/*RKC */,[1,2]/*SPA */,[2,2]/*TWE */,[,]/*UTR */,[2,0]/*WIL */],
[equipe[15][0],[0,2]/*AJA */,[2,2]/*ALM */,[1,2]/*AZ */,[1,1]/*FEY */,[1,1]/*FOR */,[1,2]/*GAE */,[1,0]/*GRO */,[,]/*HEE */,[0,0]/*HER */,[0,2]/*NAC */,[,]/*NEC */,[,]/*PEC */,[,]/*PSV */,[1,1]/*RKC */,[,]/*SPA */,[,]/*TWE */,[1,4]/*UTR */,[,]/*WIL */],
[equipe[16][0],[2,2]/*AJA */,[,]/*ALM */,[,]/*AZ */,[,]/*FEY */,[,]/*FOR */,[3,2]/*GAE */,[2,0]/*GRO */,[2,0]/*HEE */,[5,0]/*HER */,[1,0]/*NAC */,[2,0]/*NEC */,[1,1]/*PEC */,[,]/*PSV */,[2,0]/*RKC */,[1,1]/*SPA */,[,]/*TWE */,[,]/*UTR */,[6,2]/*WIL */],
[equipe[17][0],[,]/*AJA */,[0,1]/*ALM */,[0,0]/*AZ */,[0,2]/*FEY */,[2,5]/*FOR */,[3,3]/*GAE */,[,]/*GRO */,[,]/*HEE */,[1,0]/*HER */,[1,0]/*NAC */,[,]/*NEC */,[1,0]/*PEC */,[2,5]/*PSV */,[3,2]/*RKC */,[,]/*SPA */,[2,1]/*TWE */,[,]/*UTR */,[3,2]/*WIL */],
[equipe[18][0],[,]/*AJA */,[,]/*ALM */,[0,2]/*AZ */,[1,1]/*FEY */,[0,0]/*FOR */,[2,0]/*GAE */,[1,3]/*GRO */,[1,2]/*HEE */,[,]/*HER */,[2,2]/*NAC */,[4,1]/*NEC */,[,]/*PEC */,[0,2]/*PSV */,[3,0]/*RKC */,[1,2]/*SPA */,[0,1]/*TWE */,[,]/*UTR */,[,]/*WIL */]

]