var rodat = 7
var equipe = [
    [`Brasileirão Série A`,`https://oraculo.wederson.com/brasil/imagem/div1.png`,,0],
    
    [`Athlético`,`https://oraculo.wederson.com/brasil/imagem/athletico.png`,
        {
            a:7/6,
            d:7/6,
            rat:1914
        },1],
    [`Atlético`,`https://oraculo.wederson.com/brasil/imagem/atletico.png`,
        {
            a:8/rodat,
            d:10/rodat,
            rat:1914
        },2],
    [`Bahia`,`https://oraculo.wederson.com/brasil/imagem/bahia.png`,
        {
            a:8/6,
            d:3/6,
            rat:1914
        },3],
    [`Botafogo`,`https://oraculo.wederson.com/brasil/imagem/botafogo.png`,
        {
            a:8/5,
            d:11/5,
            rat:1914
        },4],
    [`Chapecoense`,`https://oraculo.wederson.com/brasil/imagem/chapecoense.png`,
        {
            a:9/5,
            d:9/5,
            rat:1776
        },5],
    [`Corinthians`,`https://oraculo.wederson.com/brasil/imagem/corinthians.png`,
        {
            a:6/6,
            d:6/6,
            rat:1914
        },6],
    [`Coritiba`,`https://oraculo.wederson.com/brasil/imagem/coritiba.png`,
        {
            a:9/rodat,
            d:6/rodat,
            rat:1914
        },7],
    [`Cruzeiro`,`https://oraculo.wederson.com/brasil/imagem/cruzeiro.png`,
        {
            a:8/rodat,
            d:16/rodat,
            rat:1914
        },8],
    [`Flamengo`,`https://oraculo.wederson.com/brasil/imagem/flamengo.png`,
        {
            a:9/5,
            d:4/5,
            rat:1914
        },9],
    [`Fluminense`,`https://oraculo.wederson.com/brasil/imagem/fluminense.png`,
        {
            a:12/rodat,
            d:8/rodat,
            rat:1914
        },10],
    [`Grêmio`,`https://oraculo.wederson.com/brasil/imagem/gremio.png`,
        {
            a:10/6,
            d:10/6,
            rat:1914
        },11],
    [`Internacional`,`https://oraculo.wederson.com/brasil/imagem/internacional.png`,
        {
            a:5/rodat,
            d:9/rodat,
            rat:1914
        },12],
    [`Mirassol`,`https://oraculo.wederson.com/brasil/imagem/mirassol.png`,
        {
            a:8/6,
            d:9/6,
            rat:1914
        },13],
    [`Palmeiras`,`https://oraculo.wederson.com/brasil/imagem/palmeiras.png`,
        {
            a:18/rodat,
            d:8/rodat,
            rat:1914
        },14],
    [`Red Bull`,`https://oraculo.wederson.com/brasil/imagem/redbull.png`,
        {
            a:5/rodat,
            d:8/rodat,
            rat:1914
        },15],
    [`Remo`,`https://oraculo.wederson.com/brasil/imagem/remo.png`,
        {
            a:6/6,
            d:11/6,
            rat:1776
        },16],
    [`Santos`,`https://oraculo.wederson.com/brasil/imagem/santos.png`,
        {
            a:10/rodat,
            d:13/rodat,
            rat:1914
        },17],
    [`São Paulo`,`https://oraculo.wederson.com/brasil/imagem/saopaulo.png`,
        {
            a:10/rodat,
            d:4/rodat,
            rat:1914
        },18],
    [`Vasco`,`https://oraculo.wederson.com/brasil/imagem/vasco.png`,
        {
            a:11/rodat,
            d:12/rodat,
            rat:1914
        },19],
    [`Vitória`,`https://oraculo.wederson.com/brasil/imagem/vitoria.png`,
        {
            a:7/5,
            d:8/5,
            rat:1914
        },20]
]