var rodat = 3
var equipe = [
    [`Brasileirão Série A`,`https://oraculo.wederson.com/brasil/imagem/div1.png`,,0],
    
    [`Athlético`,`https://oraculo.wederson.com/brasil/imagem/athletico.png`,
        {
            a:ajuste10(rodat,43/38,3),
            d:ajuste10(rodat,58/38,1),
            rat:1914
        },1],
    [`Atlético`,`https://oraculo.wederson.com/brasil/imagem/atletico.png`,
        {
            a:ajuste10(rodat,43/38,5),
            d:ajuste10(rodat,50/38,6),
            rat:1914
        },2],
    [`Bahia`,`https://oraculo.wederson.com/brasil/imagem/bahia.png`,
        {
            a:ajuste10(rodat,50/38,4),
            d:ajuste10(rodat,46/38,2),
            rat:1914
        },3],
    [`Botafogo`,`https://oraculo.wederson.com/brasil/imagem/botafogo.png`,
        {
            a:ajuste10(rodat,58/38,7),
            d:ajuste10(rodat,39/38,6),
            rat:1914
        },4],
    [`Chapecoense`,`https://oraculo.wederson.com/brasil/imagem/chapecoense.png`,
        {
            a:ajuste10(rodat,52/38*0.82,8),
            d:ajuste10(rodat,35/38*1.20,6),
            rat:1776
        },5],
    [`Corinthians`,`https://oraculo.wederson.com/brasil/imagem/corinthians.png`,
        {
            a:ajuste10(rodat,42/38,3),
            d:ajuste10(rodat,47/38,2),
            rat:1914
        },6],
    [`Coritiba`,`https://oraculo.wederson.com/brasil/imagem/coritiba.png`,
        {
            a:ajuste10(rodat,34/38,0),
            d:ajuste10(rodat,40/38,0),
            rat:1914
        },7],
    [`Cruzeiro`,`https://oraculo.wederson.com/brasil/imagem/cruzeiro.png`,
        {
            a:ajuste10(rodat,55/38,3),
            d:ajuste10(rodat,31/38,8),
            rat:1914
        },8],
    [`Flamengo`,`https://oraculo.wederson.com/brasil/imagem/flamengo.png`,
        {
            a:ajuste10(rodat,78/38,4),
            d:ajuste10(rodat,27/38,4),
            rat:1914
        },9],
    [`Fluminense`,`https://oraculo.wederson.com/brasil/imagem/fluminense.png`,
        {
            a:ajuste10(rodat,50/38,4),
            d:ajuste10(rodat,39/38,2),
            rat:1914
        },10],
    [`Grêmio`,`https://oraculo.wederson.com/brasil/imagem/gremio.png`,
        {
            a:ajuste10(rodat,47/38,6),
            d:ajuste10(rodat,50/38,7),
            rat:1914
        },11],
    [`Internacional`,`https://oraculo.wederson.com/brasil/imagem/internacional.png`,
        {
            a:ajuste10(rodat,44/38,2),
            d:ajuste10(rodat,57/38,5),
            rat:1914
        },12],
    [`Mirassol`,`https://oraculo.wederson.com/brasil/imagem/mirassol.png`,
        {
            a:ajuste10(rodat,63/38,0),
            d:ajuste10(rodat,39/38,0),
            rat:1914
        },13],
    [`Palmeiras`,`https://oraculo.wederson.com/brasil/imagem/palmeiras.png`,
        {
            a:ajuste10(rodat,66/38,10),
            d:ajuste10(rodat,33/38,4),
            rat:1914
        },14],
    [`Red Bull`,`https://oraculo.wederson.com/brasil/imagem/redbull.png`,
        {
            a:ajuste10(rodat,45/38,2),
            d:ajuste10(rodat,57/38,2),
            rat:1914
        },15],
    [`Remo`,`https://oraculo.wederson.com/brasil/imagem/remo.png`,
        {
            a:ajuste10(rodat,51/38*0.82,5),
            d:ajuste10(rodat,39/38*1.20,7),
            rat:1776
        },16],
    [`Santos`,`https://oraculo.wederson.com/brasil/imagem/santos.png`,
        {
            a:ajuste10(rodat,45/38,4),
            d:ajuste10(rodat,50/38,7),
            rat:1914
        },17],
    [`São Paulo`,`https://oraculo.wederson.com/brasil/imagem/saopaulo.png`,
        {
            a:ajuste10(rodat,43/38,5),
            d:ajuste10(rodat,47/38,2),
            rat:1914
        },18],
    [`Vasco`,`https://oraculo.wederson.com/brasil/imagem/vasco.png`,
        {
            a:ajuste10(rodat,55/38,2),
            d:ajuste10(rodat,60/38,4),
            rat:1914
        },19],
    [`Vitória`,`https://oraculo.wederson.com/brasil/imagem/vitoria.png`,
        {
            a:ajuste10(rodat,35/38,4),
            d:ajuste10(rodat,52/38,7),
            rat:1914
        },20]
]