var equipe = [
    [`League 1`,`https://oraculo.wederson.net.br/franca/imagem/ale1.png`,,0],
    
    [`Angers`,`https://oraculo.wederson.net.br/franca/imagem/angers.png`,
        {a:12/10,d:13/10},1],
    [`Auxerre`,`https://oraculo.wederson.net.br/franca/imagem/auxerre.png`,
        {a:13/10,d:16/10},2],
    [`Brest`,`https://oraculo.wederson.net.br/franca/imagem/brest.png`,
        {a:16/10,d:15/10},3],
    [`Le Havre`,`https://oraculo.wederson.net.br/franca/imagem/lehavre.png`,
        {a:12/10,d:24/10},4],
    [`Lens`,`https://oraculo.wederson.net.br/franca/imagem/lens.png`,
        {a:12/10,d:17/10},5],
    [`Lille`,`https://oraculo.wederson.net.br/franca/imagem/lille.png`,
        {a:17/10,d:10/10},6],
    [`Lyon`,`https://oraculo.wederson.net.br/franca/imagem/lyon.png`,
        {a:19/10,d:13/10},7],
    [`Marseille`,`https://oraculo.wederson.net.br/franca/imagem/marseille.png`,
        {a:21/10,d:12/10},8],
    [`Monaco`,`https://oraculo.wederson.net.br/franca/imagem/monaco.png`,
        {a:24/10,d:19/10},9],
    [`Montpellier`,`https://oraculo.wederson.net.br/franca/imagem/montpellier.png`,
        {a:8/10,d:20/10},10],
    [`Nantes`,`https://oraculo.wederson.net.br/franca/imagem/nantes.png`,
        {a:13/10,d:20/10},11],
    [`Nice`,`https://oraculo.wederson.net.br/franca/imagem/nice.png`,
        {a:23/10,d:11/10},12],
    [`PSG`,`https://oraculo.wederson.net.br/franca/imagem/psg.png`,
        {a:25/10,d:11/10},13],
    [`Reims`,`https://oraculo.wederson.net.br/franca/imagem/reims.png`,
        {a:6/10,d:20/10},14],
    [`Rennes`,`https://oraculo.wederson.net.br/franca/imagem/rennes.png`,
        {a:12/10,d:13/10},15],
    [`St-Étienne`,`https://oraculo.wederson.net.br/franca/imagem/st-etienne.png`,
        {a:13/10,d:24/10},16],
    [`Strasbourg`,`https://oraculo.wederson.net.br/franca/imagem/strasbourg.png`,
        {a:15/10,d:5/10},17],
    [`Toulouse`,`https://oraculo.wederson.net.br/franca/imagem/toulouse.png`,
        {a:12/10,d:12/10},18]
]

var tabelaRRinicial = [
    [equipe[0][0],equipe[1][0],equipe[2][0],equipe[3][0],equipe[4][0],equipe[5][0],equipe[6][0],equipe[7][0],equipe[8][0],equipe[9][0],equipe[10][0],equipe[11][0],equipe[12][0],equipe[13][0],equipe[14][0],equipe[15][0],equipe[16][0],equipe[17][0],equipe[18][0]],
    [equipe[1][0],[,]/*ANG */,[2,0]/*AUX */,[2,0]/*BRE */,[1,1]/*HAC */,[0,1]/*LEN */,[,]/*LIL */,[0,3]/*OL */,[0,2]/*OM */,[,]/*ASM */,[,]/*MON */,[1,1]/*FCN */,[1,4]/*NIC */,[2,4]/*PSG */,[1,3]/*REI */,[,]/*REN */,[4,2]/*STE */,[,]/*STR */,[,]/*TFC */],
[equipe[2][0],[1,0]/*ANG */,[,]/*AUX */,[3,0]/*BRE */,[,]/*HAC */,[2,2]/*LEN */,[0,0]/*LIL */,[,]/*OL */,[3,0]/*OM */,[0,3]/*ASM */,[,]/*MON */,[,]/*FCN */,[2,1]/*NIC */,[0,0]/*PSG */,[2,1]/*REI */,[4,0]/*REN */,[1,1]/*STE */,[,]/*STR */,[2,2]/*TFC */],
[equipe[3][0],[,]/*ANG */,[2,2]/*AUX */,[,]/*BRE */,[2,0]/*HAC */,[,]/*LEN */,[,]/*LIL */,[2,1]/*OL */,[1,5]/*OM */,[,]/*ASM */,[,]/*MON */,[4,1]/*FCN */,[0,1]/*NIC */,[2,5]/*PSG */,[,]/*REI */,[1,1]/*REN */,[4,0]/*STE */,[3,1]/*STR */,[2,0]/*TFC */],
[equipe[4][0],[0,1]/*ANG */,[3,1]/*AUX */,[0,1]/*BRE */,[,]/*HAC */,[1,2]/*LEN */,[0,3]/*LIL */,[0,4]/*OL */,[,]/*OM */,[,]/*ASM */,[1,0]/*MON */,[,]/*FCN */,[1,3]/*NIC */,[1,4]/*PSG */,[0,3]/*REI */,[,]/*REN */,[,]/*STE */,[0,3]/*STR */,[1,4]/*TFC */],
[equipe[5][0],[1,0]/*ANG */,[,]/*AUX */,[2,0]/*BRE */,[3,4]/*HAC */,[,]/*LEN */,[0,2]/*LIL */,[0,0]/*OL */,[1,3]/*OM */,[,]/*ASM */,[2,0]/*MON */,[3,2]/*FCN */,[0,0]/*NIC */,[1,2]/*PSG */,[,]/*REI */,[,]/*REN */,[,]/*STE */,[0,2]/*STR */,[0,1]/*TFC */],
[equipe[6][0],[2,0]/*ANG */,[,]/*AUX */,[3,1]/*BRE */,[1,2]/*HAC */,[,]/*LEN */,[,]/*LIL */,[1,1]/*OL */,[,]/*OM */,[2,1]/*ASM */,[,]/*MON */,[1,1]/*FCN */,[2,1]/*NIC */,[1,3]/*PSG */,[,]/*REI */,[1,0]/*REN */,[4,1]/*STE */,[3,3]/*STR */,[2,1]/*TFC */],
[equipe[7][0],[,]/*ANG */,[2,2]/*AUX */,[,]/*BRE */,[,]/*HAC */,[,]/*LEN */,[,]/*LIL */,[,]/*OL */,[2,3]/*OM */,[0,2]/*ASM */,[1,0]/*MON */,[2,0]/*FCN */,[4,1]/*NIC */,[2,3]/*PSG */,[4,0]/*REI */,[,]/*REN */,[1,0]/*STE */,[4,3]/*STR */,[0,0]/*TFC */],
[equipe[8][0],[1,1]/*ANG */,[1,3]/*AUX */,[,]/*BRE */,[5,1]/*HAC */,[,]/*LEN */,[1,1]/*LIL */,[3,2]/*OL */,[,]/*OM */,[2,1]/*ASM */,[,]/*MON */,[,]/*FCN */,[2,0]/*NIC */,[0,3]/*PSG */,[2,2]/*REI */,[,]/*REN */,[5,1]/*STE */,[1,1]/*STR */,[,]/*TFC */],
[equipe[9][0],[0,1]/*ANG */,[4,2]/*AUX */,[3,2]/*BRE */,[3,1]/*HAC */,[1,1]/*LEN */,[0,0]/*LIL */,[,]/*OL */,[,]/*OM */,[,]/*ASM */,[2,1]/*MON */,[7,1]/*FCN */,[,]/*NIC */,[2,4]/*PSG */,[3,0]/*REI */,[3,2]/*REN */,[1,0]/*STE */,[,]/*STR */,[2,0]/*TFC */],
[equipe[10][0],[1,3]/*ANG */,[3,2]/*AUX */,[3,1]/*BRE */,[,]/*HAC */,[0,2]/*LEN */,[2,2]/*LIL */,[1,4]/*OL */,[0,5]/*OM */,[2,1]/*ASM */,[,]/*MON */,[1,3]/*FCN */,[2,2]/*NIC */,[,]/*PSG */,[,]/*REI */,[,]/*REN */,[,]/*STE */,[1,1]/*STR */,[0,3]/*TFC */],
[equipe[11][0],[,]/*ANG */,[2,0]/*AUX */,[0,2]/*BRE */,[0,2]/*HAC */,[3,1]/*LEN */,[,]/*LIL */,[1,1]/*OL */,[1,2]/*OM */,[2,2]/*ASM */,[,]/*MON */,[,]/*FCN */,[1,1]/*NIC */,[,]/*PSG */,[1,2]/*REI */,[1,0]/*REN */,[2,2]/*STE */,[,]/*STR */,[,]/*TFC */],
[equipe[12][0],[,]/*ANG */,[,]/*AUX */,[,]/*BRE */,[2,1]/*HAC */,[2,0]/*LEN */,[2,2]/*LIL */,[,]/*OL */,[2,0]/*OM */,[2,1]/*ASM */,[2,0]/*MON */,[,]/*FCN */,[,]/*NIC */,[1,1]/*PSG */,[,]/*REI */,[3,2]/*REN */,[8,0]/*STE */,[2,1]/*STR */,[1,1]/*TFC */],
[equipe[13][0],[,]/*ANG */,[,]/*AUX */,[3,1]/*BRE */,[,]/*HAC */,[1,0]/*LEN */,[,]/*LIL */,[3,1]/*OL */,[,]/*OM */,[4,1]/*ASM */,[6,0]/*MON */,[1,1]/*FCN */,[,]/*NIC */,[,]/*PSG */,[1,1]/*REI */,[3,1]/*REN */,[2,1]/*STE */,[4,2]/*STR */,[3,0]/*TFC */],
[equipe[14][0],[0,1]/*ANG */,[,]/*AUX */,[1,2]/*BRE */,[1,1]/*HAC */,[0,3]/*LEN */,[0,2]/*LIL */,[1,1]/*OL */,[,]/*OM */,[0,0]/*ASM */,[4,2]/*MON */,[1,2]/*FCN */,[2,4]/*NIC */,[1,1]/*PSG */,[,]/*REI */,[2,1]/*REN */,[,]/*STE */,[,]/*STR */,[,]/*TFC */],
[equipe[15][0],[2,0]/*ANG */,[,]/*AUX */,[1,2]/*BRE */,[1,0]/*HAC */,[1,1]/*LEN */,[0,2]/*LIL */,[3,0]/*OL */,[1,2]/*OM */,[1,2]/*ASM */,[3,0]/*MON */,[,]/*FCN */,[,]/*NIC */,[,]/*PSG */,[1,0]/*REI */,[,]/*REN */,[5,0]/*STE */,[1,0]/*STR */,[0,2]/*TFC */],
[equipe[16][0],[3,3]/*ANG */,[3,1]/*AUX */,[,]/*BRE */,[0,2]/*HAC */,[0,2]/*LEN */,[1,0]/*LIL */,[,]/*OL */,[0,2]/*OM */,[,]/*ASM */,[1,0]/*MON */,[1,1]/*FCN */,[1,3]/*NIC */,[,]/*PSG */,[3,1]/*REI */,[0,2]/*REN */,[,]/*STE */,[2,0]/*STR */,[,]/*TFC */],
[equipe[17][0],[1,1]/*ANG */,[3,1]/*AUX */,[0,0]/*BRE */,[,]/*HAC */,[2,2]/*LEN */,[2,1]/*LIL */,[,]/*OL */,[1,0]/*OM */,[1,3]/*ASM */,[2,0]/*MON */,[3,1]/*FCN */,[,]/*NIC */,[,]/*PSG */,[0,0]/*REI */,[3,1]/*REN */,[,]/*STE */,[,]/*STR */,[,]/*TFC */],
[equipe[18][0],[1,1]/*ANG */,[2,0]/*AUX */,[,]/*BRE */,[2,0]/*HAC */,[,]/*LEN */,[,]/*LIL */,[1,2]/*OL */,[1,3]/*OM */,[,]/*ASM */,[1,2]/*MON */,[0,0]/*FCN */,[1,1]/*NIC */,[0,1]/*PSG */,[1,0]/*REI */,[,]/*REN */,[2,1]/*STE */,[1,2]/*STR */,[,]/*TFC */]
]