var rodat = 6
var rodat = rodat-1
var equipe = [
    [`Brasileirão Série A`,`https://oraculo.wederson.net.br/brasil/imagem/div1.png`,,0],
    
    //[`Athlético`,`https://oraculo.wederson.net.br/brasil/imagem/athletico.png`,
    // {a:50.3/rodat8,d:49.3/rodat8,rat:1932},21],
    [`Atlético`,`https://oraculo.wederson.net.br/brasil/imagem/atletico.png`,
        {a:ajuste(10,rodat,1.23,6/rodat),d:ajuste(10,rodat,1.42,8/rodat),rat:1932},1],
    //[`Atlético-GO`,`https://oraculo.wederson.net.br/brasil/imagem/atleticogo.png`,
    // {a:43.4/rodat8,d:52.8/rodat8,rat:1932},22],
    [`Bahia`,`https://oraculo.wederson.net.br/brasil/imagem/bahia.png`,
        {a:ajuste(10,rodat,1.28,6/rodat),d:ajuste(10,rodat,1.28,7/rodat),rat:1932},2],
    [`Botafogo`,`https://oraculo.wederson.net.br/brasil/imagem/botafogo.png`,
        {a:ajuste(10,rodat,1.55,6/rodat),d:ajuste(10,rodat,0.76,4/rodat),rat:1932},3],
    [`Ceará`,`https://oraculo.wederson.net.br/brasil/imagem/ceara.png`,
        {a:ajuste(10,rodat,0.95,8/rodat),d:ajuste(10,rodat,1.83,7/rodat),rat:1932},4],
    [`Corinthians`,`https://oraculo.wederson.net.br/brasil/imagem/corinthians.png`,
        {a:ajuste(10,rodat,1.42,6/rodat),d:ajuste(10,rodat,1.18,10/rodat),rat:1932},5],
    //[`Criciúma`,`https://oraculo.wederson.net.br/brasil/imagem/criciuma.png`,
    // {a:42.9/rodat8,d:64.8/rodat8,rat:1932},23],
    [`Cruzeiro`,`https://oraculo.wederson.net.br/brasil/imagem/cruzeiro.png`,
        {a:ajuste(10,rodat,1.13,7/rodat),d:ajuste(10,rodat-1,1.07,6/rodat),rat:1932},6],
    //[`Cuiabá`,`https://oraculo.wederson.net.br/brasil/imagem/cuiaba.png`,
    // {a:40.2/rodat8,d:52.9/rodat8,rat:1932},24],
    [`Flamengo`,`https://oraculo.wederson.net.br/brasil/imagem/flamengo.png`,
        {a:ajuste(10,rodat,1.60,15/rodat),d:ajuste(10,rodat,1.10,2/rodat),rat:1932},7],
    [`Fluminense`,`https://oraculo.wederson.net.br/brasil/imagem/fluminense.png`,
        {a:ajuste(10,rodat,0.86,6/rodat),d:ajuste(10,rodat,1.02,6/rodat),rat:1932},8],
    [`Fortaleza`,`https://oraculo.wederson.net.br/brasil/imagem/fortaleza.png`,
        {a:ajuste(10,rodat,1.39,5/rodat),d:ajuste(10,rodat,1.02,5/rodat),rat:1932},9],
    [`Grêmio`,`https://oraculo.wederson.net.br/brasil/imagem/gremio.png`,
        {a:ajuste(10,rodat,1.15,5/rodat),d:ajuste(10,rodat,1.31,11/rodat),rat:1932},10],
    [`Internacional`,`https://oraculo.wederson.net.br/brasil/imagem/internacional.png`,
        {a:ajuste(10,rodat,1.39,8/rodat),d:ajuste(10,rodat,0.94,4/rodat),rat:1932},11],
    [`Juventude`,`https://oraculo.wederson.net.br/brasil/imagem/juventude.png`,
        {a:ajuste(10,rodat,1.26,7/rodat),d:ajuste(10,rodat,1.55,14/rodat),rat:1932},12],
    [`Mirassol`,`https://oraculo.wederson.net.br/brasil/imagem/mirassol.png`,
        {a:ajuste(10,rodat,0.65,11/rodat),d:ajuste(10,rodat,1.74,9/rodat),rat:1932},13],
    [`Palmeiras`,`https://oraculo.wederson.net.br/brasil/imagem/palmeiras.png`,
        {a:ajuste(10,rodat,1.57,7/rodat),d:ajuste(10,rodat,0.86,3/rodat),rat:1932},14],
    [`Red Bull`,`https://oraculo.wederson.net.br/brasil/imagem/redbull.png`,
        {a:ajuste(10,rodat,1.15,8/rodat),d:ajuste(10,rodat,1.26,5/rodat),rat:1932},15],
    [`Santos`,`https://oraculo.wederson.net.br/brasil/imagem/santos.png`,
        {a:ajuste(10,rodat,0.90,3/rodat),d:ajuste(10,rodat,1.38,8/rodat),rat:1932},16],
    [`São Paulo`,`https://oraculo.wederson.net.br/brasil/imagem/saopaulo.png`,
        {a:ajuste(10,rodat,1.39,7/rodat),d:ajuste(10,rodat,1.13,9/rodat),rat:1932},17],
    [`Sport`,`https://oraculo.wederson.net.br/brasil/imagem/sport.png`,
        {a:ajuste(10,rodat,0.65,6/rodat),d:ajuste(10,rodat,1.47,5/rodat),rat:1932},18],
    [`Vasco`,`https://oraculo.wederson.net.br/brasil/imagem/vasco.png`,
        {a:ajuste(10,rodat,1.13,6/rodat),d:ajuste(10,rodat,1.47,8/rodat),rat:1932},19],
    [`Vitória`,`https://oraculo.wederson.net.br/brasil/imagem/vitoria.png`,
        {a:ajuste(10,rodat,1.18,7/rodat),d:ajuste(10,rodat,1.36,9/rodat),rat:1932},20]
]

var tabelaRRinicial = [
    [equipe[0][0],equipe[1][0],equipe[2][0],equipe[3][0],equipe[4][0],equipe[5][0],equipe[6][0],equipe[7][0],equipe[8][0],equipe[9][0],equipe[10][0],equipe[11][0],equipe[12][0],equipe[13][0],equipe[14][0],equipe[15][0],equipe[16][0],equipe[17][0],equipe[18][0],equipe[19][0],equipe[20][0]],
    [equipe[1][0],[,]/*ATM */,[,]/*BAH */,[1,0]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[0,0]/*SPA */,[,]/*SPT */,[,]/*VAS */,[2,2]/*VIT */],
    [equipe[2][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[1,0]/*CEA */,[1,1]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[1,1]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[3][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[2,0]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[2,0]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[2,2]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[4][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[2,0]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[1,1]/*SPA */,[,]/*SPT */,[2,1]/*VAS */,[,]/*VIT */],
    [equipe[5][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[0,2]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[2,1]/*SPT */,[3,0]/*VAS */,[,]/*VIT */],
    [equipe[6][0],[,]/*ATM */,[3,0]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[2,1]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[1,0]/*VAS */,[,]/*VIT */],
    [equipe[7][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[4,0]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[1,1]/*INT */,[6,0]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[8][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[2,1]/*RBB */,[1,0]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[1,1]/*VIT */],
    [equipe[9][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[2,0]/*FLU */,[,]/*FOR */,[,]/*GRE */,[0,0]/*INT */,[,]/*JUV */,[,]/*MIR */,[1,2]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[10][0],[2,1]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[0,2]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[1,1]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[11][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[3,0]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[3,1]/*JUV */,[,]/*MIR */,[0,1]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[12][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[2,1]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[2,2]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[2,0]/*VIT */],
    [equipe[13][0],[2,2]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[1,1]/*FOR */,[4,1]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[14][0],[,]/*ATM */,[0,1]/*BAH */,[0,0]/*BOT */,[,]/*CEA */,[2,0]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[15][0],[,]/*ATM */,[,]/*BAH */,[1,0]/*BOT */,[2,2]/*CEA */,[,]/*COR */,[1,0]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[16][0],[2,0]/*ATM */,[2,2]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[1,2]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[17][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[1,1]/*CRU */,[,]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[2,1]/*SAN */,[,]/*SPA */,[0,0]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[18][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[,]/*FLA */,[,]/*FLU */,[0,0]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[1,2]/*PAL */,[0,1]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[19][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[0,0]/*FLA */,[,]/*FLU */,[,]/*FOR */,[,]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[2,1]/*SAN */,[,]/*SPA */,[3,1]/*SPT */,[,]/*VAS */,[,]/*VIT */],
    [equipe[20][0],[,]/*ATM */,[,]/*BAH */,[,]/*BOT */,[,]/*CEA */,[,]/*COR */,[,]/*CRU */,[1,2]/*FLA */,[,]/*FLU */,[2,1]/*FOR */,[1,1]/*GRE */,[,]/*INT */,[,]/*JUV */,[,]/*MIR */,[,]/*PAL */,[,]/*RBB */,[,]/*SAN */,[,]/*SPA */,[,]/*SPT */,[,]/*VAS */,[,]/*VIT */]
]
