var rodat = 10
var equipe = [
    [`Brasileirão Série A`,`http://oraculo.wederson.com/brasil/imagem/div1.png`,,0],
    
    //[`Athlético`,`http://oraculo.wederson.com/brasil/imagem/athletico.png`,
    // {a:50.3/rodat8,d:49.3/rodat8,rat:1932},21],
    [`Atlético`,`http://oraculo.wederson.com/brasil/imagem/atletico.png`,
        {a:13/rodat,d:9/rodat,rat:1932},1],
    //[`Atlético-GO`,`http://oraculo.wederson.com/brasil/imagem/atleticogo.png`,
    // {a:43.4/rodat,d:52.8/rodat8,rat:1932},22],
    [`Bahia`,`http://oraculo.wederson.com/brasil/imagem/bahia.png`,
        {a:13/rodat,d:6/rodat,rat:1932},2],
    [`Botafogo`,`http://oraculo.wederson.com/brasil/imagem/botafogo.png`,
        {a:13/rodat,d:4/rodat,rat:1932},3],
    [`Ceará`,`http://oraculo.wederson.com/brasil/imagem/ceara.png`,
        {a:9/rodat,d:8/rodat,rat:1932},4],
    [`Corinthians`,`http://oraculo.wederson.com/brasil/imagem/corinthians.png`,
        {a:11/rodat,d:12/rodat,rat:1932},5],
    //[`Criciúma`,`http://oraculo.wederson.com/brasil/imagem/criciuma.png`,
    // {a:42.9/rodat8,d:64.8/rodat8,rat:1932},23],
    [`Cruzeiro`,`http://oraculo.wederson.com/brasil/imagem/cruzeiro.png`,
        {a:17/rodat,d:4/rodat,rat:1932},6],
    //[`Cuiabá`,`http://oraculo.wederson.com/brasil/imagem/cuiaba.png`,
    // {a:40.2/rodat8,d:52.9/rodat8,rat:1932},24],
    [`Flamengo`,`http://oraculo.wederson.com/brasil/imagem/flamengo.png`,
        {a:16/rodat,d:3/rodat,rat:1932},7],
    [`Fluminense`,`http://oraculo.wederson.com/brasil/imagem/fluminense.png`,
        {a:12/rodat,d:12/rodat,rat:1932},8],
    [`Fortaleza`,`http://oraculo.wederson.com/brasil/imagem/fortaleza.png`,
        {a:9/rodat,d:17/rodat,rat:1932},9],
    [`Grêmio`,`http://oraculo.wederson.com/brasil/imagem/gremio.png`,
        {a:11/rodat,d:11/rodat,rat:1932},10],
    [`Internacional`,`http://oraculo.wederson.com/brasil/imagem/internacional.png`,
        {a:9/rodat,d:17/rodat,rat:1932},11],
    [`Juventude`,`http://oraculo.wederson.com/brasil/imagem/juventude.png`,
        {a:8/rodat,d:22/rodat,rat:1932},12],
    [`Mirassol`,`http://oraculo.wederson.com/brasil/imagem/mirassol.png`,
        {a:16/rodat,d:10/rodat,rat:1932},13],
    [`Palmeiras`,`http://oraculo.wederson.com/brasil/imagem/palmeiras.png`,
        {a:12/rodat,d:10/rodat,rat:1932},14],
    [`Red Bull`,`http://oraculo.wederson.com/brasil/imagem/redbull.png`,
        {a:13/rodat,d:10/rodat,rat:1932},15],
    [`Santos`,`http://oraculo.wederson.com/brasil/imagem/santos.png`,
        {a:9/rodat,d:9/rodat,rat:1932},16],
    [`São Paulo`,`http://oraculo.wederson.com/brasil/imagem/saopaulo.png`,
        {a:9/rodat,d:15/rodat,rat:1932},17],
    [`Sport`,`http://oraculo.wederson.com/brasil/imagem/sport.png`,
        {a:3/rodat,d:16/rodat,rat:1932},18],
    [`Vasco`,`http://oraculo.wederson.com/brasil/imagem/vasco.png`,
        {a:9/rodat,d:12/rodat,rat:1932},19],
    [`Vitória`,`http://oraculo.wederson.com/brasil/imagem/vitoria.png`,
        {a:5/rodat,d:8/rodat,rat:1932},20]
]